export const supportedCountries = [
  { value: "Argentina", label: "Argentina" },
  { value: "Australia", label: "Australia *" },
  { value: "Austria", label: "Austria *" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Belgium", label: "Belgium *" },
  { value: "Brazil", label: "Brazil *" },
  { value: "Canada", label: "Canada *" },
  { value: "Chile", label: "Chile" },
  { value: "China", label: "China" },
  { value: "Colombia", label: "Colombia" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Czech Republic", label: "Czech Republic" },
  { value: "Denmark", label: "Denmark" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Egypt", label: "Egypt" },
  { value: "Finland", label: "Finland" },
  { value: "France", label: "France *" },
  { value: "Germany", label: "Germany *" },
  { value: "Greece", label: "Greece" },
  { value: "Hong Kong", label: "Hong Kong *" },
  { value: "Hungary", label: "Hungary" },
  { value: "India", label: "India *" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Ireland", label: "Ireland *" },
  { value: "Israel", label: "Israel" },
  { value: "Italy", label: "Italy *" },
  { value: "Japan", label: "Japan" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Mexico", label: "Mexico *" },
  { value: "Morocco", label: "Morocco" },
  { value: "Netherlands", label: "Netherlands *" },
  { value: "New Zealand", label: "New Zealand *" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Norway", label: "Norway" },
  { value: "Oman", label: "Oman" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Panama", label: "Panama" },
  { value: "Peru", label: "Peru" },
  { value: "Philippines", label: "Philippines" },
  { value: "Poland", label: "Poland" },
  { value: "Portugal", label: "Portugal" },
  { value: "Qatar", label: "Qatar" },
  { value: "Romania", label: "Romania" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Singapore", label: "Singapore *" },
  { value: "South Africa", label: "South Africa" },
  { value: "South Korea", label: "South Korea" },
  { value: "Spain", label: "Spain *" },
  { value: "Sweden", label: "Sweden" },
  { value: "Switzerland", label: "Switzerland *" },
  { value: "Taiwan", label: "Taiwan" },
  { value: "Thailand", label: "Thailand" },
  { value: "Turkey", label: "Turkey" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "UK", label: "UK *" },
  { value: "USA", label: "USA *" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Venezuela", label: "Venezuela" },
  { value: "Vietnam", label: "Vietnam *" },
];